Fetch deferred drawable from attribute
Backbase/DeferredResources pull request #41
Opened 2020-10-31 17:41 UTC by MarinKacaj

Added DeferredDrawable.Attribute class, which mimics the functionality, implementation, documentation and tests of the DeferredDrawable.Resource class, with the only difference being the resolution of the drawable from an attribute instead of a drawable resource id.

2020-11-02 14:29 UTC, drewhamilton requested changes
Thanks for the contribution! This looks great, I've just added a few requests and I'm curious to find out why this test is failing...

2020-11-02 14:29 UTC, drewhamilton commented on deferred-resources/src/androidTest/res/values/test_theme.xml
> +    <item name="homeAsUpIndicator">@drawable/oval</item>
All of the tests refer to `android.R.attr.homeAsUpIndicator`, so I don't think this non-android one is needed. If that's the case can you remove it from this test theme so only necessary attributes are set?

2020-11-02 14:29 UTC, drewhamilton commented on deferred-resources/src/main/java/com/backbase/deferredresources/DeferredDrawable.kt
> +        @AttrRes private val attrId: Int,
Can you rename this to `resId` to match the parameter to `resolveAttribute` as well as other `Deferred*.Attribute` constructors?

2020-11-02 14:29 UTC, drewhamilton commented on deferred-resources/src/main/java/com/backbase/deferredresources/DeferredDrawable.kt
> +            @AttrRes attrId: Int,
Same

2020-11-02 14:29 UTC, drewhamilton commented on deferred-resources/src/main/java/com/backbase/deferredresources/DeferredDrawable.kt
> +                context.theme.resolveAttribute(attrId, this, true)
Can you use this library's internal `Context.resolveAttribute` extension? It ensures the type of the resolved value is correct, and throws a nicely-formatted error message if not.

Also can you reuse a single `TypedValue` instance so that a new one is not constructed on each `resolve` call?

2020-11-02 14:29 UTC, drewhamilton commented on deferred-resources/src/androidTest/java/com/backbase/deferredresources/DeferredDrawableTest.kt
> +        assertThat(loadedAgain.gradientRadiusCompat).isEqualTo(0.5f)
It's surprising that this fails on API 22 – suggests it's getting mutated even with `mutate = false`... Can you also `assumeFalse` for API 22 for now? I'm curious to see what happens on higher APIs.

2020-11-02 16:12 UTC, MarinKacaj commented on deferred-resources/src/androidTest/java/com/backbase/deferredresources/DeferredDrawableTest.kt
> +        assertThat(loadedAgain.gradientRadiusCompat).isEqualTo(0.5f)
On my machine, API 23 seems OK.

2020-11-02 16:16 UTC, MarinKacaj commented on deferred-resources/src/androidTest/java/com/backbase/deferredresources/DeferredDrawableTest.kt
> +        assertThat(loadedAgain.gradientRadiusCompat).isEqualTo(0.5f)
Updated the PR

2020-11-03 08:26 UTC, drewhamilton commented on deferred-resources/src/androidTest/java/com/backbase/deferredresources/DeferredDrawableTest.kt
> +        assertThat(loadedAgain.gradientRadiusCompat).isEqualTo(0.5f)
Weeeird, will have to investigate this some day.

2020-11-03 08:39 UTC, drewhamilton commented on deferred-resources/src/main/java/com/backbase/deferredresources/DeferredDrawable.kt
> +                    TypedValue.TYPE_STRING // could be initially interpreted a string, e.g. "res/drawable/oval.xml"
Which of these three cases occur in your tests? I ask because of `Resources`' documentation for the `resolveRefs` parameter:
> If true, resource references will be walked; if false, `outValue` may be a TYPE_REFERENCE.  In either case, it will never be a TYPE_ATTRIBUTE.

That doc sounds like you won't get TYPE_REFERENCE since you're using `resolveRefs = true`... but since you are ultimately resolving the drawable with `resourceId` it seems like you _are_ getting TYPE_REFERENCE.

And if that's correct but you get a TYPE_STRING... will `resourceId` still work?

2020-11-03 08:39 UTC, drewhamilton commented on demo/src/main/java/com/backbase/deferredresources/demo/DemoPagerAdapter.kt
> +    override fun getItemCount(): Int = ViewType.values().size
Nice 😁

2020-11-03 08:54 UTC, MarinKacaj commented on deferred-resources/src/main/java/com/backbase/deferredresources/DeferredDrawable.kt
> +                    TypedValue.TYPE_STRING // could be initially interpreted a string, e.g. "res/drawable/oval.xml"
This was tricky. What was returned was actually a string like "res/drawable/oval.xml", and also a `resourceId`, but the `type` field of the `TypedValue` is actually `TYPE_STRING`.
I agree that it's not going to be `TYPE_ATTRIBUTE` most probably, but I cannot see how the type is determined.

2020-11-03 08:59 UTC, drewhamilton commented on deferred-resources/src/main/java/com/backbase/deferredresources/DeferredDrawable.kt
> +                    TypedValue.TYPE_STRING // could be initially interpreted a string, e.g. "res/drawable/oval.xml"
Weird. I wonder if it holds on to the `resourceId` as a "backup" of sorts, or if it just happens to still be there as a side effect of internal logic.

Anyway, can you remove TYPE_ATTRIBUTE from the list then? Then the PR should be all set.

2020-11-03 11:00 UTC, MarinKacaj commented on deferred-resources/src/main/java/com/backbase/deferredresources/DeferredDrawable.kt
> +                    TypedValue.TYPE_STRING // could be initially interpreted a string, e.g. "res/drawable/oval.xml"
Updated the PR

2020-11-03 11:03 UTC, drewhamilton approved these changes

2020-11-03 12:33 UTC, merged